version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - REACT_APP_STAGE=staging npm run build
  post_build:
    commands:
      # Build app, upload it to S3, and invalidate the CloudFront cache.
      - npm run deploy
artifacts:
  files:
    - '**/*'
  base-directory: build